eureka:
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true
server:
  port: 9999
spring:
  application:
    name: gateway-server
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888

  data:
    redis:
      host: localhost
      port: 6379
      password: qwer

# cloud gateway for exposing into eureka
  cloud:
    gateway:
      server:
        webflux:        # with the real project it really risks if exposed routes with eureka
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
          httpclient:
            connect-timeout: 1000
            response-timeout: 5s
          routes:
            - id: pipeline
              uri: lb://pipeline
              predicates:
                - Path=/pipeline/**
              filters:
                - RewritePath=/pipeline/(?<segment>.*),/$\{segment}
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    redis-rate-limiter.requestedTokens: 1


#                - name: Retry
#                  args:
#                    retries: 5
#                    statuses: BAD_GATEWAY
#                    methods: GET
#                    backoff:
#                      firstBackoff: 10ms
#                      maxBackoff: 50ms
#                      factor: 2
#                      basedOnPreviousValue: false



            #     - name: CircuitBreaker
#                  args:
#                    name: pipelineCircuitBreaker
#                    fallbackUri: forward:/fallback/pipeline
            
            # Account Route
            - id: account
              uri: lb://account
              predicates:
                - Path=/account/**
              filters:
                - RewritePath=/account/(?<segment>.*),/$\{segment}
                - name: CircuitBreaker
                  args:
                    name: accountCircuitBreaker
                    fallbackUri: forward:/fallback/pipeline
                #    name: pipelineCircuitBreaker
                  # fallbackUri: forward:/fallback/pipeline-service/client/account/secured

  #                    statusCode:
#                      - 500 # Internal Server Error
#                      - 503 # Service Unavailable
#                      - 404 # Not Found
  # Security Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090
      client:
        provider:
          itp-standard:
            issuer-uri: http://localhost:9090
        registration:
          itp-standard:
            provider: itp-standard
            client-id: itp-standard
            client-secret: qwerqwer
            redirect-uri: http://localhost:9999/login/oauth2/code/itp-standard
            authorization-grant-type:
              - authorization_code
              - client_credentials
              - refresh_token
            scope:
              - openid
              - profile
              - email

# Resilience4J (Circuit Breaker)
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        failure-rate-threshold: 50
        permitted-number-of-calls-in-half-open-state: 2
        wait-duration-in-open-state: 10000

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"